services:
  api:
    build:
      context: .
      dockerfile: node.dockerfile
    image: node-custom
    volumes:
      - ./src:/app/src
    ports:
      - "8080:8080"
    networks:
      - visitor-dev-network
    environment:
      - MYSQL_HOST=host.docker.internal
      - MYSQL_USER=root
      - MYSQL_DB_NAME=test
      - ENVIROMENT=development
      - MYSQL_PASSWORD=12345
    command: ["npm", "run", "start"]

  db:
    image: mysql:latest
    ports:
      - "3307:3306"
    volumes:
      - visitor-db-data:/var/lib/mysql
      - ./visitor-dump.sql:/home/visitor-dump.sql
      - ./dump-init.sh:/home/dump-init.sh
    networks:
      - visitor-dev-network
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=test
      - MYSQL_USER=root
      - MYSQL_PASSWORD=12345
    

  phpmyadmin:
    image: phpmyadmin:latest
    networks:
      - visitor-dev-network
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=12345
      - PMA_ARBITRARY=1
    ports:
      - 80:80

volumes:
  visitor-db-data:

networks:
  visitor-dev-network:
