name: Visitor-backend-CD

on:
  workflow_run:
    workflows: ["visitor-backend-CI"]
    types: [completed]
    branches:
      - main

env:
  IMAGE_NAME: ${{vars.DOCKER_HUB_USERNAME}}/${{vars.IMAGE_NAME}}

jobs:
  validate:
    runs-on: ubuntu-latest
    if: ${{github.event.workflow_run.conclusion == 'success'}}

    steps:
      - name: validate if previous worlflow ran succesfully
        run: |
          echo "can proceed"

  push-artifact-to-duckerhub:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{vars.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_TOKEN}}

      - name: build image
        run: |
          docker image build -f node.dockerfile -t ${{env.IMAGE_NAME}} .

      - name: push to docker hub
        run: |
          docker image push ${{env.IMAGE_NAME}}

  deply-to-aws-lambda:
    runs-on: ubuntu-latest

    steps:
      - name: serverless deploy
        uses: serverless/github-action@v3.2
        with:
          args: -c "cd . && serverless deploy"
          entrypoint: /bin/sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
